# Generated by Django 5.1.5 on 2025-02-01 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDetect',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'type_detects',
            },
        ),
        migrations.CreateModel(
            name='HistoryDetect',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=25, unique=True)),
                ('image_detect_id', models.CharField(max_length=100, unique=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_detect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app_server.typedetect')),
            ],
            options={
                'db_table': 'history_detects',
            },
        ),
    ]
