# Generated by Django 5.1.5 on 2025-02-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('face_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
