# Generated by Django 5.1.5 on 2025-02-04 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app_server', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydetect',
            name='user_id',
        ),
        migrations.AddField(
            model_name='historydetect',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare_app_server.user'),
        ),
    ]
