# Generated by Django 5.1.5 on 2025-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app_server', '0003_remove_historydetect_user_id_historydetect_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_image',
        ),
        migrations.AddField(
            model_name='user',
            name='face_detect_data',
            field=models.TextField(default=''),
        ),
    ]
