# Generated by Django 5.1.7 on 2025-04-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app_server', '0004_remove_user_face_image_user_face_detect_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydetect',
            name='type_detect_id',
        ),
        migrations.RemoveField(
            model_name='historydetect',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='face_detect_data',
            new_name='face_encode_value',
        ),
        migrations.DeleteModel(
            name='TypeDetect',
        ),
        migrations.DeleteModel(
            name='HistoryDetect',
        ),
    ]
