spring:
  application:
    name: api_gateway_service
  main:
    web-application-type: reactive
server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
    version: openapi_3_1
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Authenticate Service API
        url: /authenticate/v3/api-docs
      - name: Admin Service API
        url: /admin/v3/api-docs
      - name: Appointment Service API
        url: /appointment/v3/api-docs
